// app/head.tsx
export default function Head() {
  return (
    <>
      <title>Jarves App</title>
      <meta name="description" content="Generated by me :)" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
