import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Navbar } from '@/components/navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de">
      <body className={`${inter.className} bg-slate-50`}>
        <Navbar />
        <div className="min-w-full flex items-center w-full mx-auto px-4 sm:px-6 lg:px-8 ">
          <div className="min-w-full flex items-center justify-between container mx-auto my-5 px-5 lg:px-10 ">{children}</div>
        </div>
      </body>
    </html>
  );
}
