'use client';

import React, { useState, useEffect, useMemo } from 'react';
import {
  ColumnDef,
  ColumnFiltersState,
  SortingState,
  VisibilityState,
  flexRender,
  getCoreRowModel,
  getFilteredRowModel,
  getPaginationRowModel,
  getSortedRowModel,
  useReactTable,
  Row,
  HeaderContext,
  CellContext,
} from '@tanstack/react-table';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Checkbox } from '@/components/ui/checkbox';
import {
  DropdownMenu,
  DropdownMenuCheckboxItem,
  DropdownMenuContent,
  DropdownMenuTrigger,
  DropdownMenuItem,
  DropdownMenuSeparator,
} from '@/components/ui/dropdown-menu';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger, DialogFooter } from '@/components/ui/dialog';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { DataTablePagination } from '@/components/ui/data-table-pagination';
import { ChevronDown, ArrowUpDown, EyeOff, Star, Filter } from 'lucide-react';
import { ScrollArea, ScrollBar } from '@/components/ui/scroll-area';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { Calendar } from '@/components/ui/calendar';
import { DateRange } from 'react-day-picker';
import { format } from 'date-fns';
import { de } from 'date-fns/locale';
import { Slider } from '@/components/ui/slider';
import { Label } from '@/components/ui/label';
import BulkActionSidebar from '../BulkActionSidebar';
import Link from 'next/link';

interface Kontaktperson {
  id: string;
  autogeneratedNr: number;
  email: string | null;
  anrede: string | null;
  betreuerId: string | null;
  duAnsprache: boolean;
  erstelltAm: string;
  kategorie: string | null;
  letzteAenderungAm: string | null;
  linkedin: string | null;
  mobil: string | null;
  nachname: string;
  notiz: string | null;
  positionJobtitel: string | null;
  status: string;
  telefon: string | null;
  titel: string | null;
  vorname: string;
  xing: string | null;
  betreuer: {
    id: string;
    name: string;
  } | null;
  unternehmen: {
    id: string;
    name: string;
  }[];
  [key: string]: any;
}

const columnLabels: { [key: string]: string } = {
  autogeneratedNr: 'Kontaktnummer',
  nachname: 'Nachname',
  vorname: 'Vorname',
  email: 'E-Mail',
  anrede: 'Anrede',
  duAnsprache: 'Du-Ansprache',
  kategorie: 'Kategorie',
  status: 'Status',
  telefon: 'Telefon',
  mobil: 'Mobil',
  positionJobtitel: 'Position/Jobtitel',
  titel: 'Titel',
  linkedin: 'LinkedIn',
  xing: 'Xing',
  notiz: 'Notiz',
  erstelltAm: 'Erstellt Am',
  letzteAenderungAm: 'Letzte Änderung Am',
  betreuer: 'Betreuer',
  unternehmen: 'Unternehmen',
};

const standardColumns: (keyof Kontaktperson)[] = ['autogeneratedNr', 'nachname', 'vorname', 'status', 'unternehmen', 'email', 'telefon', 'betreuer'];

const DateRangeFilter: React.FC<{ column: any }> = ({ column }) => {
  const [date, setDate] = useState<DateRange | undefined>({
    from: undefined,
    to: undefined,
  });

  useEffect(() => {
    column.setFilterValue(date);
  }, [date, column]);

  const resetFilter = () => {
    setDate({ from: undefined, to: undefined });
    column.setFilterValue(undefined);
  };

  return (
    <div className="flex flex-col space-y-2 p-2">
      <div className="flex flex-col space-y-2">
        <Calendar
          initialFocus
          mode="range"
          defaultMonth={date?.from}
          selected={date}
          onSelect={setDate}
          numberOfMonths={2}
          locale={de}
          className="w-full max-w-[250px]"
        />
      </div>
      {(date?.from || date?.to) && (
        <div className="flex flex-col space-y-2">
          <div className="text-xs">
            {date.from && `Von: ${format(date.from, 'dd.MM.yyyy')}`}
            {date.to && ` - Bis: ${format(date.to, 'dd.MM.yyyy')}`}
          </div>
          <Button variant="ghost" size="sm" onClick={resetFilter} className="text-xs py-1 h-7">
            Filter zurücksetzen
          </Button>
        </div>
      )}
    </div>
  );
};

const NumberRangeFilter: React.FC<{ column: any }> = ({ column }) => {
  const [range, setRange] = useState<[number, number]>([0, 100]);

  useEffect(() => {
    column.setFilterValue(range);
  }, [range, column]);

  const handleRangeChange = (newValue: number[]) => {
    setRange(newValue as [number, number]);
  };

  const resetFilter = () => {
    setRange([0, 100]);
    column.setFilterValue(undefined);
  };

  return (
    <div className="flex flex-col space-y-2 p-2">
      <Label>Nummernbereich</Label>
      <Slider min={0} max={100} step={1} value={range} onValueChange={handleRangeChange} className="w-full" />
      <div className="flex justify-between text-sm text-muted-foreground">
        <span>{range[0]}</span>
        <span>{range[1]}</span>
      </div>
      <Button variant="ghost" size="sm" onClick={resetFilter} className="mt-2">
        Filter zurücksetzen
      </Button>
    </div>
  );
};

const StatusSelectFilter: React.FC<{ column: any; options: string[] }> = ({ column, options }) => {
  const [selectedValue, setSelectedValue] = useState<string | ''>('');

  useEffect(() => {
    column.setFilterValue(selectedValue || undefined);
  }, [selectedValue, column]);

  const handleReset = () => {
    setSelectedValue('');
    column.setFilterValue(undefined);
  };

  return (
    <div className="space-y-2">
      <Select value={selectedValue} onValueChange={(value) => setSelectedValue(value)}>
        <SelectTrigger>
          <SelectValue placeholder="Filter auswählen" />
        </SelectTrigger>
        <SelectContent>
          {options.map((option) => (
            <SelectItem key={option} value={option}>
              {option}
            </SelectItem>
          ))}
        </SelectContent>
      </Select>
      {selectedValue && (
        <Button variant="ghost" size="sm" onClick={handleReset}>
          Filter zurücksetzen
        </Button>
      )}
    </div>
  );
};

const createColumns = (data: Kontaktperson[]): ColumnDef<Kontaktperson>[] => {
  const allFields = new Set<string>();
  data.forEach((item) => Object.keys(item).forEach((key) => allFields.add(key)));

  allFields.delete('id');

  return Array.from(allFields).map(
    (key): ColumnDef<Kontaktperson> => ({
      accessorKey: key,
      header: ({ column }: HeaderContext<Kontaktperson, unknown>) => {
        const isNameColumn = key === 'nachname' || key === 'vorname';

        return (
          <div className="flex items-center space-x-2">
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button
                  variant="ghost"
                  size="sm"
                  className={`-ml-3 h-8 data-[state=open]:bg-accent ${isNameColumn ? 'ml-0' : ''}`}
                  aria-label={`${columnLabels[key] || key} Optionen`}
                >
                  <span>{columnLabels[key] || key.charAt(0).toUpperCase() + key.slice(1)}</span>
                  <ChevronDown className="ml-2 h-4 w-4" />
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="start" className="w-80 p-4">
                <div className="text-base font-semibold mb-2">Optionen für {columnLabels[key] || key}</div>
                <div className="border-b my-2"></div>
                <div className="mb-4">
                  <div className="font-medium">Sortieren</div>
                  <DropdownMenuItem onClick={() => column.toggleSorting(false)}>
                    <ArrowUpDown className="mr-2 h-3.5 w-3.5 text-muted-foreground/70" />
                    Aufsteigend
                  </DropdownMenuItem>
                  <DropdownMenuItem onClick={() => column.toggleSorting(true)}>
                    <ArrowUpDown className="mr-2 h-3.5 w-3.5 text-muted-foreground/70" />
                    Absteigend
                  </DropdownMenuItem>
                </div>
                <div className="border-b my-2"></div>
                <div>
                  <div className="font-medium mb-2">Filter</div>
                  {key === 'erstelltAm' || key === 'letzteAenderungAm' ? (
                    <DateRangeFilter column={column} />
                  ) : key === 'autogeneratedNr' ? (
                    <NumberRangeFilter column={column} />
                  ) : key === 'status' ? (
                    <StatusSelectFilter column={column} options={['Aktiv', 'Inaktiv', 'Interessent']} />
                  ) : key === 'kategorie' ? (
                    <StatusSelectFilter column={column} options={['A', 'B', 'C', 'D']} />
                  ) : isNameColumn ? (
                    <div className="text-sm text-gray-600">Kein Filter verfügbar</div>
                  ) : (
                    <Input
                      placeholder="Suchen..."
                      value={(column.getFilterValue() as string) ?? ''}
                      onChange={(event) => column.setFilterValue(event.target.value)}
                      className="max-w-sm"
                    />
                  )}
                </div>
                <div className="text-sm text-gray-600 mt-4"></div>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>
        );
      },
      cell: ({ row }: CellContext<Kontaktperson, unknown>) => {
        const value = row.getValue(key);
        if (key === 'nachname' || key === 'vorname') {
          return (
            <Link href={`/kontakte/${row.original.id}`} className="text-blue-600 hover:underline" target="_blank" rel="noopener noreferrer">
              {value as string}
            </Link>
          );
        }
        if (key === 'betreuer') {
          return <div className="w-[200px]">{(value as Kontaktperson['betreuer'])?.name || '-'}</div>;
        }
        if (key === 'unternehmen') {
          const unternehmen = value as Kontaktperson['unternehmen'];
          return (
            <div className="w-[200px]">
              {unternehmen.map((u, index) => (
                <Link key={u.id} href={`/kunden/${u.id}`} className="text-blue-600 hover:underline" target="_blank" rel="noopener noreferrer">
                  {u.name}
                  {index < unternehmen.length - 1 ? ', ' : ''}
                </Link>
              ))}
            </div>
          );
        }
        if (key === 'erstelltAm' || key === 'letzteAenderungAm') {
          return <div className="w-[100px]">{value ? format(new Date(value as string), 'dd.MM.yyyy') : '-'}</div>;
        }
        if (key === 'telefon' || key === 'mobil') {
          return value ? (
            <Link href={`tel:${value}`} className="text-blue-600 hover:underline">
              {value as string}
            </Link>
          ) : (
            '-'
          );
        }
        if (key === 'email') {
          return value ? (
            <Link href={`mailto:${value}`} className="text-blue-600 hover:underline">
              {value as string}
            </Link>
          ) : (
            '-'
          );
        }
        if (key === 'linkedin' || key === 'xing') {
          return value ? (
            <Link href={value as string} target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:underline">
              {value as string}
            </Link>
          ) : (
            '-'
          );
        }
        if (typeof value === 'boolean') {
          return <div className="w-[100px]">{value ? 'Ja' : 'Nein'}</div>;
        }
        return <div className="w-[200px]">{value?.toString() || '-'}</div>;
      },
      sortingFn: key === 'autogeneratedNr' ? 'basic' : undefined,
      filterFn: (row: Row<Kontaktperson>, id: string, filterValue: any) => {
        if (key === 'autogeneratedNr') {
          const value = row.getValue(id) as number;
          const [min, max] = filterValue as [number, number];
          return value >= min && value <= max;
        }
        if (key === 'erstelltAm' || key === 'letzteAenderungAm') {
          const date = row.getValue(id) as string;
          const cellDate = new Date(date);
          const { from, to } = filterValue as DateRange;

          if (from && to) {
            return cellDate >= from && cellDate <= to;
          }
          if (from) {
            return cellDate >= from;
          }
          if (to) {
            return cellDate <= to;
          }
          return true;
        }
        const cellValue = row.getValue(id);
        if (typeof cellValue === 'string') {
          return cellValue.toLowerCase().includes((filterValue as string).toLowerCase());
        }
        return String(cellValue)
          .toLowerCase()
          .includes((filterValue as string).toLowerCase());
      },
    })
  );
};

export function KontaktpersonenList() {
  const [sorting, setSorting] = useState<SortingState>([]);
  const [columnFilters, setColumnFilters] = useState<ColumnFiltersState>([]);
  const [columnVisibility, setColumnVisibility] = useState<VisibilityState>({});
  const [rowSelection, setRowSelection] = useState({});
  const [data, setData] = useState<Kontaktperson[]>([]);
  const [filterLetter, setFilterLetter] = useState('ALL');
  const [isBulkActionSidebarOpen, setIsBulkActionSidebarOpen] = useState(false);
  const [newStatus, setNewStatus] = useState('');
  const [newBetreuer, setNewBetreuer] = useState('');
  const [newKategorie, setNewKategorie] = useState('');
  const [betreuerList, setBetreuerList] = useState<{ id: string; name: string }[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchKontaktpersonen = async () => {
      setIsLoading(true);
      setError(null);
      try {
        const response = await fetch('/api/getKontaktpersonenTest');
        if (!response.ok) {
          throw new Error(`HTTP error! status: ${response.status}`);
        }
        const kontaktpersonen = await response.json();
        setData(kontaktpersonen);
      } catch (error) {
        console.error('Fehler beim Laden der Kontaktpersonen:', error);
        setError('Fehler beim Laden der Kontaktpersonen. Bitte versuchen Sie es später erneut.');
      } finally {
        setIsLoading(false);
      }
    };
    fetchKontaktpersonen();
  }, []);

  useEffect(() => {
    const fetchBetreuerList = async () => {
      try {
        const response = await fetch('/api/getBetreuerList');
        if (response.ok) {
          const data = await response.json();
          setBetreuerList(data);
        }
      } catch (error) {
        console.error('Fehler beim Laden der Betreuer:', error);
      }
    };

    fetchBetreuerList();
  }, []);

  const columns = useMemo(() => {
    const allColumns = createColumns(data);
    const selectColumn: ColumnDef<Kontaktperson> = {
      id: 'select',
      header: ({ table }) => (
        <Checkbox
          checked={table.getIsAllPageRowsSelected()}
          onCheckedChange={(value) => table.toggleAllPageRowsSelected(!!value)}
          aria-label="Alle auswählen"
        />
      ),
      cell: ({ row }) => (
        <Checkbox checked={row.getIsSelected()} onCheckedChange={(value) => row.toggleSelected(!!value)} aria-label="Zeile auswählen" />
      ),
      enableSorting: false,
      enableHiding: false,
    };
    return [selectColumn, ...allColumns];
  }, [data]);

  useEffect(() => {
    const initialVisibility: VisibilityState = {};
    columns.forEach((column) => {
      if ('accessorKey' in column && typeof column.accessorKey === 'string') {
        initialVisibility[column.accessorKey] = standardColumns.includes(column.accessorKey as keyof Kontaktperson);
      }
    });
    setColumnVisibility(initialVisibility);
  }, [columns]);

  const availableLetters = useMemo(() => {
    const letters = new Set(data.map((kontaktperson) => kontaktperson.nachname?.[0]?.toUpperCase()).filter(Boolean));
    return Array.from(letters).sort();
  }, [data]);

  const filteredData = useMemo(() => {
    if (filterLetter === 'ALL') return data;
    return data.filter((kontaktperson) => kontaktperson.nachname?.toUpperCase().startsWith(filterLetter));
  }, [data, filterLetter]);

  const table = useReactTable({
    data: filteredData,
    columns,
    onSortingChange: setSorting,
    onColumnFiltersChange: setColumnFilters,
    getCoreRowModel: getCoreRowModel(),
    getPaginationRowModel: getPaginationRowModel(),
    getSortedRowModel: getSortedRowModel(),
    getFilteredRowModel: getFilteredRowModel(),
    onColumnVisibilityChange: setColumnVisibility,
    onRowSelectionChange: setRowSelection,
    state: {
      sorting,
      columnFilters,
      columnVisibility,
      rowSelection,
    },
    getRowId: (row) => row.id,
    filterFns: {
      custom: (row, columnId, filterValue) => {
        const column = columns.find((col) => 'accessorKey' in col && col.accessorKey === columnId);
        if (column && 'filterFn' in column) {
          return (column.filterFn as any)(row, columnId, filterValue);
        }
        return true;
      },
    },
  });

  const handleFilterChange = (letter: string) => {
    setFilterLetter(letter);
    table.resetPageIndex();
  };

  const handleBulkUpdate = async () => {
    const selectedIds = Object.keys(rowSelection);
    if (selectedIds.length === 0) return;

    const updates = {
      status: newStatus || undefined,
      kategorie: newKategorie || undefined,
      betreuerId: newBetreuer || undefined,
    };

    try {
      const response = await fetch('/api/bulkUpdateKontaktpersonen', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ ids: selectedIds, updates }),
      });

      if (response.ok) {
        console.log('Massenaktualisierung erfolgreich durchgeführt');
        const updatedData = await fetch('/api/getKontaktpersonenTest').then((res) => res.json());
        setData(updatedData);
        setIsBulkActionSidebarOpen(false);
        setRowSelection({});
        setNewStatus('');
        setNewKategorie('');
        setNewBetreuer('');
      } else {
        console.error('Fehler bei der Durchführung der Massenaktualisierung');
      }
    } catch (error) {
      console.error('Fehler bei der Durchführung der Massenaktualisierung:', error);
    }
  };

  const handleBulkDelete = async () => {
    const selectedIds = Object.keys(rowSelection);
    if (selectedIds.length === 0) return;

    try {
      const response = await fetch('/api/bulkDeleteKontaktpersonen', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ ids: selectedIds }),
      });

      if (response.ok) {
        console.log('Massenlöschung erfolgreich durchgeführt');
        const updatedData = await fetch('/api/getKontaktpersonenTest').then((res) => res.json());
        setData(updatedData);
        setIsBulkActionSidebarOpen(false);
        setRowSelection({});
      } else {
        console.error('Fehler bei der Durchführung der Massenlöschung');
      }
    } catch (error) {
      console.error('Fehler bei der Durchführung der Massenlöschung:', error);
    }
  };

  if (isLoading) {
    return <div>Lade Kontaktpersonen...</div>;
  }

  if (error) {
    return <div>Fehler: {error}</div>;
  }

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div className="flex items-center space-x-2 overflow-x-auto">
          <Button variant={filterLetter === 'ALL' ? 'default' : 'outline'} onClick={() => handleFilterChange('ALL')}>
            ALLE
          </Button>
          {availableLetters.map((letter) => (
            <Button key={letter} variant={filterLetter === letter ? 'default' : 'outline'} onClick={() => handleFilterChange(letter)}>
              {letter}
            </Button>
          ))}
        </div>
        <div className="flex items-center space-x-2">
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="outline" className="ml-auto">
                Spalten <ChevronDown className="ml-2 h-4 w-4" />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              {table
                .getAllColumns()
                .filter((column) => column.id !== 'select' && typeof column.accessorFn !== 'undefined')
                .map((column) => {
                  return (
                    <DropdownMenuCheckboxItem
                      key={column.id}
                      className="capitalize"
                      checked={column.getIsVisible()}
                      onCheckedChange={(value) => column.toggleVisibility(!!value)}
                    >
                      {columnLabels[column.id] || column.id}
                    </DropdownMenuCheckboxItem>
                  );
                })}
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      </div>
      <div className="rounded-md border bg-white">
        <ScrollArea className="w-full overflow-auto" style={{ maxWidth: '100%' }}>
          <Table style={{ minWidth: '1000px' }}>
            <TableHeader>
              {table.getHeaderGroups().map((headerGroup) => (
                <TableRow key={headerGroup.id}>
                  {headerGroup.headers.map((header) => (
                    <TableHead key={header.id} className="bg-gray-100">
                      {header.isPlaceholder ? null : flexRender(header.column.columnDef.header, header.getContext())}
                    </TableHead>
                  ))}
                </TableRow>
              ))}
            </TableHeader>
            <TableBody>
              {table.getRowModel().rows?.length ? (
                table.getRowModel().rows.map((row) => (
                  <TableRow key={row.id} data-state={row.getIsSelected() && 'selected'}>
                    {row.getVisibleCells().map((cell) => (
                      <TableCell key={cell.id}>{flexRender(cell.column.columnDef.cell, cell.getContext())}</TableCell>
                    ))}
                  </TableRow>
                ))
              ) : (
                <TableRow>
                  <TableCell colSpan={columns.length} className="h-24 text-center">
                    Keine Ergebnisse.
                  </TableCell>
                </TableRow>
              )}
            </TableBody>
          </Table>
          <ScrollBar orientation="horizontal" />
        </ScrollArea>
      </div>
      <DataTablePagination table={table} />
      <div className="flex justify-end">
        <Button variant="outline" onClick={() => setIsBulkActionSidebarOpen(true)} disabled={Object.keys(rowSelection).length === 0}>
          Massenbearbeitung
        </Button>
      </div>
      <BulkActionSidebar
        isOpen={isBulkActionSidebarOpen}
        selectedCount={Object.keys(rowSelection).length}
        onClose={() => setIsBulkActionSidebarOpen(false)}
        newStatus={newStatus}
        setNewStatus={setNewStatus}
        newBetreuer={newBetreuer}
        setNewBetreuer={setNewBetreuer}
        newKategorie={newKategorie}
        setNewKategorie={setNewKategorie}
        onDelete={handleBulkDelete}
        onUpdate={handleBulkUpdate}
        betreuerList={betreuerList}
        newVerknuepfung={''}
        setNewVerknuepfung={function (value: string): void {
          throw new Error('Function not implemented.');
        }}
      />
    </div>
  );
}
