import React, { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { FaStar } from 'react-icons/fa'; // Import der Stern-Icon-Komponente

const Stammdaten: React.FC<{ unternehmen: any }> = ({ unternehmen }) => {
  const [editing, setEditing] = useState(false);
  const [formData, setFormData] = useState(unternehmen);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  // Funktion zum Rendern von Sternen basierend auf der Kategorie
  const renderStars = (rating: number) => {
    return (
      <div style={{ display: 'flex', gap: '2px' }}>
        {Array.from({ length: 5 }, (_, i) => (
          <FaStar key={i} color={i < rating ? 'gold' : 'gray'} />
        ))}
      </div>
    );
  };

  return (
    <form className="grid grid-cols-1 gap-6 w-full p-4 text-sm">
      <div className="grid grid-cols-2 gap-6">
        {' '}
        {/* Zwei Spalten Layout */}
        {/* Linke Spalte */}
        <div className="space-y-4">
          <div>
            <label className="block text-gray-700 font-bold mb-2">Kundennummer</label>
            <div className="bg-gray-100 p-2 rounded min-h-10 flex items-center">{unternehmen.autogeneratedNr}</div>
          </div>
          <div>
            <label className="block text-gray-700 font-bold mb-2">Kundenname</label>
            <div className="bg-gray-100 p-2 rounded min-h-10 flex items-center">{unternehmen.name}</div>
          </div>
          <div>
            <label className="block text-gray-700 font-bold mb-2">Straße</label>
            <div className="bg-gray-100 p-2 rounded min-h-10 flex items-center">{unternehmen.strasse}</div>
          </div>
          <div>
            <label className="block text-gray-700 font-bold mb-2">Postleitzahl</label>
            <div className="bg-gray-100 p-2 rounded min-h-10 flex items-center">{unternehmen.postleitzahl}</div>
          </div>
          <div>
            <label className="block text-gray-700 font-bold mb-2">Stadt</label>
            <div className="bg-gray-100 p-2 rounded min-h-10 flex items-center">{unternehmen.stadt}</div>
          </div>
          <div>
            <label className="block text-gray-700 font-bold mb-2">Standort</label>
            <div className="bg-gray-100 p-2 rounded min-h-10 flex items-center">{unternehmen.standort}</div>
          </div>
          <div className="h-20"></div> {/* Spacer */}
          <div>
            <label className="block text-gray-700 font-bold mb-2">Homepage</label>
            <div className="bg-gray-100 p-2 rounded min-h-10 flex items-center">{unternehmen.homepage}</div>
          </div>
          <div>
            <label className="block text-gray-700 font-bold mb-2">Jobpage</label>
            <div className="bg-gray-100 p-2 rounded min-h-10 flex items-center">{unternehmen.jobsite}</div>
          </div>
          <div>
            <label className="block text-gray-700 font-bold mb-2">LinkedIn</label>
            <div className="bg-gray-100 p-2 rounded min-h-10 flex items-center">{unternehmen.linkedin}</div>
          </div>
          <div>
            <label className="block text-gray-700 font-bold mb-2">Xing</label>
            <div className="bg-gray-100 p-2 rounded min-h-10 flex items-center">{unternehmen.xing}</div>
          </div>
        </div>
        {/* Rechte Spalte */}
        <div className="space-y-4">
          <div>
            <label className="block text-gray-700 font-bold mb-2">Status</label>
            <div className="bg-gray-100 p-2 rounded min-h-10 flex items-center">{unternehmen.status}</div>
          </div>
          <div>
            <label className="block text-gray-700 font-bold mb-2">Kategorie (Sterne 1-5)</label>
            <div className="min-h-10 flex items-center">{renderStars(unternehmen.kategorie)}</div>
          </div>
          <div className="h-20"></div> {/* Spacer */}
          <div>
            <label className="block text-gray-700 font-bold mb-2">Zentrale Mail</label>
            <div className="bg-gray-100 p-2 rounded min-h-10 flex items-center">{unternehmen.zentraleMail}</div>
          </div>
          <div>
            <label className="block text-gray-700 font-bold mb-2">Zentrale Telefonnummer</label>
            <div className="bg-gray-100 p-2 rounded min-h-10 flex items-center">{unternehmen.zentralTelefon}</div>
          </div>
          <div>
            <label className="block text-gray-700 font-bold mb-2">Hauptansprechpartner</label>
            <div className="bg-gray-100 p-2 rounded min-h-10 flex items-center">Dummy Name</div>
          </div>
          <div>
            <label className="block text-gray-700 font-bold mb-2">Vermittlungsprovision %</label>
            <div className="bg-gray-100 p-2 rounded min-h-10 flex items-center">{unternehmen.vermittlungsprovision}</div>
          </div>
          <div>
            <label className="block text-gray-700 font-bold mb-2">Vermittlungsprovision Auszahlungsintervall</label>
            <div className="bg-gray-100 p-2 rounded min-h-10 flex items-center">{unternehmen.vermittlungsprovisionIntervall}</div>
          </div>
          <div className="h-20"></div> {/* Spacer */}
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-gray-700 font-bold mb-2">Interner Betreuer</label>
              <div className="bg-gray-100 p-2 rounded min-h-10 flex items-center">{unternehmen.internerBetreuer}</div>
            </div>
            <div>
              <label className="block text-gray-700 font-bold mb-2">Affiliate</label>
              <div className="bg-gray-100 p-2 rounded min-h-10 flex items-center">{unternehmen.affiliate}</div>
            </div>
            <div>
              <label className="block text-gray-700 font-bold mb-2">Angelegt am</label>
              <div className="bg-gray-100 p-2 rounded min-h-10 flex items-center">{unternehmen.angelegtAm}</div>
            </div>
            <div>
              <label className="block text-gray-700 font-bold mb-2">Angelegt von</label>
              <div className="bg-gray-100 p-2 rounded min-h-10 flex items-center">{unternehmen.angelegtVon}</div>
            </div>
          </div>
        </div>
      </div>

      {/* Bereich unter den zwei Spalten */}
      <div>
        <label className="block text-gray-700 font-bold mb-2">USP's</label>
        <Textarea className="w-full h-40 bg-gray-100" defaultValue={unternehmen.usbBeschreibung} />
      </div>
      <div>
        <label className="block text-gray-700 font-bold mb-2">Sonstige Notizen zum Unternehmen</label>
        <Textarea className="w-full h-40 bg-gray-100" defaultValue={unternehmen.interneNotizen} />
      </div>
    </form>
  );
};

export default Stammdaten;
